import type { NextConfig } from 'next'

const nextConfig: NextConfig = {
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'hotsanjana.in',
      },
    ],
    formats: ['image/avif', 'image/webp'],
  },
  async redirects() {
    return [
      // Static pages
      { source: '/about.html', destination: '/about', permanent: true },
      { source: '/contact.html', destination: '/contact', permanent: true },
      { source: '/gallery.html', destination: '/gallery', permanent: true },
      { source: '/location.html', destination: '/location', permanent: true },
      { source: '/services.html', destination: '/services', permanent: true },
      { source: '/types.html', destination: '/types', permanent: true },
      // Verification pages
      { source: '/google6171968c473325b9.html', destination: '/', permanent: false },
      { source: '/googleec00ed53af076a45.html', destination: '/', permanent: false },

      // Old escort location pages (escorts-xxx.html)
      { source: '/escorts-airoli.html', destination: '/escorts/airoli', permanent: true },
      { source: '/escorts-ambernath.html', destination: '/escorts/ambernath', permanent: true },
      { source: '/escorts-ambivali.html', destination: '/escorts/ambivali', permanent: true },
      { source: '/escorts-andheri.html', destination: '/escorts/andheri', permanent: true },
      { source: '/escorts-asangaon.html', destination: '/escorts/asangaon', permanent: true },
      { source: '/escorts-badlapur.html', destination: '/escorts/badlapur', permanent: true },
      { source: '/escorts-bandra.html', destination: '/escorts/bandra', permanent: true },
      { source: '/escorts-belapur.html', destination: '/escorts/belapur', permanent: true },
      { source: '/escorts-bhandup.html', destination: '/escorts/bhandup', permanent: true },
      { source: '/escorts-bhayander.html', destination: '/escorts/bhayander', permanent: true },
      { source: '/escorts-bhiwandi.html', destination: '/escorts/bhiwandi', permanent: true },
      { source: '/escorts-boisar.html', destination: '/escorts/boisar', permanent: true },
      { source: '/escorts-borivali.html', destination: '/escorts/borivali', permanent: true },
      { source: '/escorts-byculla.html', destination: '/escorts/byculla', permanent: true },
      { source: '/escorts-cbd-belapur.html', destination: '/escorts/cbd-belapur', permanent: true },
      { source: '/escorts-chembur.html', destination: '/escorts/chembur', permanent: true },
      { source: '/escorts-churchgate.html', destination: '/escorts/churchgate', permanent: true },
      { source: '/escorts-colaba.html', destination: '/escorts/colaba', permanent: true },
      { source: '/escorts-cst.html', destination: '/escorts/cst', permanent: true },
      { source: '/escorts-dadar.html', destination: '/escorts/dadar', permanent: true },
      { source: '/escorts-dahisar.html', destination: '/escorts/dahisar', permanent: true },
      { source: '/escorts-diva.html', destination: '/escorts/diva', permanent: true },
      { source: '/escorts-dombivali.html', destination: '/escorts/dombivali', permanent: true },
      { source: '/escorts-ghansoli.html', destination: '/escorts/ghansoli', permanent: true },
      { source: '/escorts-ghatkopar.html', destination: '/escorts/ghatkopar', permanent: true },
      { source: '/escorts-ghodbunder.html', destination: '/escorts/ghodbunder', permanent: true },
      { source: '/escorts-goregaon.html', destination: '/escorts/goregaon', permanent: true },
      { source: '/escorts-govandi.html', destination: '/escorts/govandi', permanent: true },
      { source: '/escorts-grant-road.html', destination: '/escorts/grant-road', permanent: true },
      { source: '/escorts-indore.html', destination: '/escorts/indore', permanent: true },
      { source: '/escorts-jogeshwari.html', destination: '/escorts/jogeshwari', permanent: true },
      { source: '/escorts-juhu.html', destination: '/escorts/juhu', permanent: true },
      { source: '/escorts-juinagar.html', destination: '/escorts/juinagar', permanent: true },
      { source: '/escorts-kalamboli.html', destination: '/escorts/kalamboli', permanent: true },
      { source: '/escorts-kalwa.html', destination: '/escorts/kalwa', permanent: true },
      { source: '/escorts-kalyan.html', destination: '/escorts/kalyan', permanent: true },
      { source: '/escorts-kamothe.html', destination: '/escorts/kamothe', permanent: true },
      { source: '/escorts-kandivali.html', destination: '/escorts/kandivali', permanent: true },
      { source: '/escorts-kanjurmarg.html', destination: '/escorts/kanjurmarg', permanent: true },
      { source: '/escorts-karjat.html', destination: '/escorts/karjat', permanent: true },
      { source: '/escorts-kasara.html', destination: '/escorts/kasara', permanent: true },
      { source: '/escorts-khar.html', destination: '/escorts/khar', permanent: true },
      { source: '/escorts-kharghar.html', destination: '/escorts/kharghar', permanent: true },
      { source: '/escorts-khopoli.html', destination: '/escorts/khopoli', permanent: true },
      { source: '/escorts-kopar-khairane.html', destination: '/escorts/kopar-khairane', permanent: true },
      { source: '/escorts-kurla.html', destination: '/escorts/kurla', permanent: true },
      { source: '/escorts-lokhandwala.html', destination: '/escorts/lokhandwala', permanent: true },
      { source: '/escorts-lower-parel.html', destination: '/escorts/lower-parel', permanent: true },
      { source: '/escorts-mahalaxmi.html', destination: '/escorts/mahalaxmi', permanent: true },
      { source: '/escorts-mahim.html', destination: '/escorts/mahim', permanent: true },
      { source: '/escorts-malad.html', destination: '/escorts/malad', permanent: true },
      { source: '/escorts-mankhurd.html', destination: '/escorts/mankhurd', permanent: true },
      { source: '/escorts-marine-lines.html', destination: '/escorts/marine-lines', permanent: true },
      { source: '/escorts-matunga.html', destination: '/escorts/matunga', permanent: true },
      { source: '/escorts-mira-road.html', destination: '/escorts/mira-road', permanent: true },
      { source: '/escorts-mulund.html', destination: '/escorts/mulund', permanent: true },
      { source: '/escorts-mumbai-airport.html', destination: '/escorts/mumbai-airport', permanent: true },
      { source: '/escorts-mumbai-central.html', destination: '/escorts/mumbai-central', permanent: true },
      { source: '/escorts-mumbra.html', destination: '/escorts/mumbra', permanent: true },
      { source: '/escorts-nahur.html', destination: '/escorts/nahur', permanent: true },
      { source: '/escorts-naigaon.html', destination: '/escorts/naigaon', permanent: true },
      { source: '/escorts-nalasopara.html', destination: '/escorts/nalasopara', permanent: true },
      { source: '/escorts-navi-mumbai.html', destination: '/escorts/navi-mumbai', permanent: true },
      { source: '/escorts-neral.html', destination: '/escorts/neral', permanent: true },
      { source: '/escorts-nerul.html', destination: '/escorts/nerul', permanent: true },
      { source: '/escorts-palghar.html', destination: '/escorts/palghar', permanent: true },
      { source: '/escorts-panvel.html', destination: '/escorts/panvel', permanent: true },
      { source: '/escorts-parel.html', destination: '/escorts/parel', permanent: true },
      { source: '/escorts-powai.html', destination: '/escorts/powai', permanent: true },
      { source: '/escorts-prabhadevi.html', destination: '/escorts/prabhadevi', permanent: true },
      { source: '/escorts-pune.html', destination: '/escorts/pune', permanent: true },
      { source: '/escorts-rabale.html', destination: '/escorts/rabale', permanent: true },
      { source: '/escorts-sakinaka.html', destination: '/escorts/sakinaka', permanent: true },
      { source: '/escorts-sanpada.html', destination: '/escorts/sanpada', permanent: true },
      { source: '/escorts-santacruz.html', destination: '/escorts/santacruz', permanent: true },
      { source: '/escorts-saphale.html', destination: '/escorts/saphale', permanent: true },
      { source: '/escorts-seawoods.html', destination: '/escorts/seawoods', permanent: true },
      { source: '/escorts-sion.html', destination: '/escorts/sion', permanent: true },
      { source: '/escorts-thakurli.html', destination: '/escorts/thakurli', permanent: true },
      { source: '/escorts-thane.html', destination: '/escorts/thane', permanent: true },
      { source: '/escorts-titwala.html', destination: '/escorts/titwala', permanent: true },
      { source: '/escorts-turbhe.html', destination: '/escorts/turbhe', permanent: true },
      { source: '/escorts-ulhasnagar.html', destination: '/escorts/ulhasnagar', permanent: true },
      { source: '/escorts-ulwe.html', destination: '/escorts/ulwe', permanent: true },
      { source: '/escorts-vasai.html', destination: '/escorts/vasai', permanent: true },
      { source: '/escorts-vashi.html', destination: '/escorts/vashi', permanent: true },
      { source: '/escorts-versova.html', destination: '/escorts/versova', permanent: true },
      { source: '/escorts-vidyavihar.html', destination: '/escorts/vidyavihar', permanent: true },
      { source: '/escorts-vikhroli.html', destination: '/escorts/vikhroli', permanent: true },
      { source: '/escorts-vile-parle.html', destination: '/escorts/vile-parle', permanent: true },
      { source: '/escorts-virar.html', destination: '/escorts/virar', permanent: true },
      { source: '/escorts-wadala.html', destination: '/escorts/wadala', permanent: true },
      { source: '/escorts-worli.html', destination: '/escorts/worli', permanent: true },

      // Old call-girls location pages
      { source: '/call-girls-in-airoli.html', destination: '/call-girls/airoli', permanent: true },
      { source: '/call-girls-in-ambernath.html', destination: '/call-girls/ambernath', permanent: true },
      { source: '/call-girls-in-ambivali.html', destination: '/call-girls/ambivali', permanent: true },
      { source: '/call-girls-in-andheri.html', destination: '/call-girls/andheri', permanent: true },
      { source: '/call-girls-in-asangaon.html', destination: '/call-girls/asangaon', permanent: true },
      { source: '/call-girls-in-badlapur.html', destination: '/call-girls/badlapur', permanent: true },
      { source: '/call-girls-in-bandra.html', destination: '/call-girls/bandra', permanent: true },
      { source: '/call-girls-in-belapur.html', destination: '/call-girls/belapur', permanent: true },
      { source: '/call-girls-in-bhandup.html', destination: '/call-girls/bhandup', permanent: true },
      { source: '/call-girls-in-bhayander.html', destination: '/call-girls/bhayander', permanent: true },
      { source: '/call-girls-in-bhiwandi.html', destination: '/call-girls/bhiwandi', permanent: true },
      { source: '/call-girls-in-boisar.html', destination: '/call-girls/boisar', permanent: true },
      { source: '/call-girls-in-borivali.html', destination: '/call-girls/borivali', permanent: true },
      { source: '/call-girls-in-byculla.html', destination: '/call-girls/byculla', permanent: true },
      { source: '/call-girls-in-cbd-belapur.html', destination: '/call-girls/cbd-belapur', permanent: true },
      { source: '/call-girls-in-chembur.html', destination: '/call-girls/chembur', permanent: true },
      { source: '/call-girls-in-churchgate.html', destination: '/call-girls/churchgate', permanent: true },
      { source: '/call-girls-in-colaba.html', destination: '/call-girls/colaba', permanent: true },
      { source: '/call-girls-in-cst.html', destination: '/call-girls/cst', permanent: true },
      { source: '/call-girls-in-dadar.html', destination: '/call-girls/dadar', permanent: true },
      { source: '/call-girls-in-dahisar.html', destination: '/call-girls/dahisar', permanent: true },
      { source: '/call-girls-in-diva.html', destination: '/call-girls/diva', permanent: true },
      { source: '/call-girls-in-dombivali.html', destination: '/call-girls/dombivali', permanent: true },
      { source: '/call-girls-in-ghansoli.html', destination: '/call-girls/ghansoli', permanent: true },
      { source: '/call-girls-in-ghatkopar.html', destination: '/call-girls/ghatkopar', permanent: true },
      { source: '/call-girls-in-ghodbunder.html', destination: '/call-girls/ghodbunder', permanent: true },
      { source: '/call-girls-in-goregaon.html', destination: '/call-girls/goregaon', permanent: true },
      { source: '/call-girls-in-govandi.html', destination: '/call-girls/govandi', permanent: true },
      { source: '/call-girls-in-grant-road.html', destination: '/call-girls/grant-road', permanent: true },
      { source: '/call-girls-in-indore.html', destination: '/call-girls/indore', permanent: true },
      { source: '/call-girls-in-jogeshwari.html', destination: '/call-girls/jogeshwari', permanent: true },
      { source: '/call-girls-in-juhu.html', destination: '/call-girls/juhu', permanent: true },
      { source: '/call-girls-in-juinagar.html', destination: '/call-girls/juinagar', permanent: true },
      { source: '/call-girls-in-kalamboli.html', destination: '/call-girls/kalamboli', permanent: true },
      { source: '/call-girls-in-kalwa.html', destination: '/call-girls/kalwa', permanent: true },
      { source: '/call-girls-in-kalyan.html', destination: '/call-girls/kalyan', permanent: true },
      { source: '/call-girls-in-kamothe.html', destination: '/call-girls/kamothe', permanent: true },
      { source: '/call-girls-in-kandivali.html', destination: '/call-girls/kandivali', permanent: true },
      { source: '/call-girls-in-kanjurmarg.html', destination: '/call-girls/kanjurmarg', permanent: true },
      { source: '/call-girls-in-karjat.html', destination: '/call-girls/karjat', permanent: true },
      { source: '/call-girls-in-kasara.html', destination: '/call-girls/kasara', permanent: true },
      { source: '/call-girls-in-khar.html', destination: '/call-girls/khar', permanent: true },
      { source: '/call-girls-in-kharghar.html', destination: '/call-girls/kharghar', permanent: true },
      { source: '/call-girls-in-khopoli.html', destination: '/call-girls/khopoli', permanent: true },
      { source: '/call-girls-in-kopar-khairane.html', destination: '/call-girls/kopar-khairane', permanent: true },
      { source: '/call-girls-in-kurla.html', destination: '/call-girls/kurla', permanent: true },
      { source: '/call-girls-in-lokhandwala.html', destination: '/call-girls/lokhandwala', permanent: true },
      { source: '/call-girls-in-lower-parel.html', destination: '/call-girls/lower-parel', permanent: true },
      { source: '/call-girls-in-mahalaxmi.html', destination: '/call-girls/mahalaxmi', permanent: true },
      { source: '/call-girls-in-mahim.html', destination: '/call-girls/mahim', permanent: true },
      { source: '/call-girls-in-malad.html', destination: '/call-girls/malad', permanent: true },
      { source: '/call-girls-in-mankhurd.html', destination: '/call-girls/mankhurd', permanent: true },
      { source: '/call-girls-in-marine-lines.html', destination: '/call-girls/marine-lines', permanent: true },
      { source: '/call-girls-in-matunga.html', destination: '/call-girls/matunga', permanent: true },
      { source: '/call-girls-in-mira-road.html', destination: '/call-girls/mira-road', permanent: true },
      { source: '/call-girls-in-mulund.html', destination: '/call-girls/mulund', permanent: true },
      { source: '/call-girls-in-mumbai-airport.html', destination: '/call-girls/mumbai-airport', permanent: true },
      { source: '/call-girls-in-mumbai-central.html', destination: '/call-girls/mumbai-central', permanent: true },
      { source: '/call-girls-in-mumbai.html', destination: '/call-girls/mumbai', permanent: true },
      { source: '/call-girls-in-mumbra.html', destination: '/call-girls/mumbra', permanent: true },
      { source: '/call-girls-in-nahur.html', destination: '/call-girls/nahur', permanent: true },
      { source: '/call-girls-in-naigaon.html', destination: '/call-girls/naigaon', permanent: true },
      { source: '/call-girls-in-nalasopara.html', destination: '/call-girls/nalasopara', permanent: true },
      { source: '/call-girls-in-navi-mumbai.html', destination: '/call-girls/navi-mumbai', permanent: true },
      { source: '/call-girls-in-neral.html', destination: '/call-girls/neral', permanent: true },
      { source: '/call-girls-in-nerul.html', destination: '/call-girls/nerul', permanent: true },
      { source: '/call-girls-in-palghar.html', destination: '/call-girls/palghar', permanent: true },
      { source: '/call-girls-in-panvel.html', destination: '/call-girls/panvel', permanent: true },
      { source: '/call-girls-in-parel.html', destination: '/call-girls/parel', permanent: true },
      { source: '/call-girls-in-powai.html', destination: '/call-girls/powai', permanent: true },
      { source: '/call-girls-in-prabhadevi.html', destination: '/call-girls/prabhadevi', permanent: true },
      { source: '/call-girls-in-pune.html', destination: '/call-girls/pune', permanent: true },
      { source: '/call-girls-in-rabale.html', destination: '/call-girls/rabale', permanent: true },
      { source: '/call-girls-in-sakinaka.html', destination: '/call-girls/sakinaka', permanent: true },
      { source: '/call-girls-in-sanpada.html', destination: '/call-girls/sanpada', permanent: true },
      { source: '/call-girls-in-santacruz.html', destination: '/call-girls/santacruz', permanent: true },
      { source: '/call-girls-in-saphale.html', destination: '/call-girls/saphale', permanent: true },
      { source: '/call-girls-in-seawoods.html', destination: '/call-girls/seawoods', permanent: true },
      { source: '/call-girls-in-sion.html', destination: '/call-girls/sion', permanent: true },
      { source: '/call-girls-in-thakurli.html', destination: '/call-girls/thakurli', permanent: true },
      { source: '/call-girls-in-thane.html', destination: '/call-girls/thane', permanent: true },
      { source: '/call-girls-in-titwala.html', destination: '/call-girls/titwala', permanent: true },
      { source: '/call-girls-in-turbhe.html', destination: '/call-girls/turbhe', permanent: true },
      { source: '/call-girls-in-ulhasnagar.html', destination: '/call-girls/ulhasnagar', permanent: true },
      { source: '/call-girls-in-ulwe.html', destination: '/call-girls/ulwe', permanent: true },
      { source: '/call-girls-in-vasai.html', destination: '/call-girls/vasai', permanent: true },
      { source: '/call-girls-in-vashi.html', destination: '/call-girls/vashi', permanent: true },
      { source: '/call-girls-in-versova.html', destination: '/call-girls/versova', permanent: true },
      { source: '/call-girls-in-vidyavihar.html', destination: '/call-girls/vidyavihar', permanent: true },
      { source: '/call-girls-in-vikhroli.html', destination: '/call-girls/vikhroli', permanent: true },
      { source: '/call-girls-in-vile-parle.html', destination: '/call-girls/vile-parle', permanent: true },
      { source: '/call-girls-in-virar.html', destination: '/call-girls/virar', permanent: true },
      { source: '/call-girls-in-wadala.html', destination: '/call-girls/wadala', permanent: true },
      { source: '/call-girls-in-worli.html', destination: '/call-girls/worli', permanent: true },

      // Escort type pages
      { source: '/bengali-escorts-mumbai.html', destination: '/escort-types/bengali', permanent: true },
      { source: '/girlfriend-escorts-mumbai.html', destination: '/escort-types/girlfriend', permanent: true },
      { source: '/hj-bj-expert-escorts-mumbai.html', destination: '/escort-types/hj-bj-expert', permanent: true },
      { source: '/house-wife-mumbai.html', destination: '/escort-types/housewife', permanent: true },
      { source: '/local-escorts-mumbai.html', destination: '/escort-types/local', permanent: true },
      { source: '/nepali-escorts-mumbai.html', destination: '/escort-types/nepali', permanent: true },
      { source: '/north-indian-escorts-mumbai.html', destination: '/escort-types/north-indian', permanent: true },
      { source: '/punjabi-escorts-mumbai.html', destination: '/escort-types/punjabi', permanent: true },
      { source: '/russian-escorts-mumbai.html', destination: '/escort-types/russian', permanent: true },
      { source: '/unsatisfied-bhabhi-mumbai.html', destination: '/escort-types/unsatisfied-bhabhi', permanent: true },
      { source: '/unsatisfied-female-mumbai.html', destination: '/escort-types/unsatisfied-female', permanent: true },
      { source: '/vip-escorts-mumbai.html', destination: '/escort-types/vip', permanent: true },
    ]
  },
}

export default nextConfig
